### ISSUE TITLE
The API is not working

### ISSUE THREAD

**Issue by pcodesdev** [VishwaGauravIn/github-twitter-card-embed#3]
I have added the following in my readme file and nothing that is working:
<a href="https://gtce.itsvg.in/"><img src="https://gtce.itsvg.in/api?username=PcodesDev&theme=dracula&icon=hashtag&time=true&response=true&border=true"/></a>

**Comment by VishwaGauravIn** [comment]
> I have added the following in my readme file and nothing that is working: [![](https://camo.githubusercontent.com/0b466851617e8e12728fb6e0833a9a96fa29be265c38ecce8855cdb9b3e20784/68747470733a2f2f677463652e69747376672e696e2f6170693f757365726e616d653d50636f646573446576267468656d653d64726163756c612669636f6e3d686173687461672674696d653d7472756526726573706f6e73653d7472756526626f726465723d74727565)](https://gtce.itsvg.in/)

Due to recent Twitter API pricing changes, we are not able to provide this service free for now but we are looking for a way around.
