### ISSUE TITLE
Twitter card not showing up in GitHub profile.

### ISSUE THREAD

**Issue by dheerajy1** [VishwaGauravIn/github-twitter-card-embed#4]
## Description
I wanted to add Twitter card that shows my latest tweet. I followed the instructions on the [website](https://github.com/VishwaGauravIn/github-twitter-card-embed) to get the link for the card and added it to my README.md file. But something went wrong…

### Problem

The Twitter card is not showing up in my profile! It’s just a blank space where the card should be. I don’t know what I did wrong or how to fix it.
The markdown I got from website : 

- `[![](https://gtce.itsvg.in/api?username=yssdheeraj&theme=dracula&response=true&border=true&time=true&icon=default)](https://github.com/VishwaGauravIn/github-twitter-card-embed)`

### Possible cause

- I noticed that the website uses the domain twitter.com for the card, but Twitter has recently changed its domain to x.com, because of Elon. 
- Could this be the reason why the card is not working? If so, how can I update the domain in the card?

Thank you.

**Comment by VishwaGauravIn** [comment]
Hi, Dheeraj thanks for reaching out. We have actually paused this project due to recent API changes of Twitter (X). We are still looking for a way around and it will automatically get fixed once we get an alternate way.
